---


- name: ansible host
  hosts: ansible
  become: yes
  roles:
    - ansible

- name: ansible host
  hosts: phone
  become: yes
  roles:
    - phone

- name: common tasks
  hosts: all
  become: yes
  roles:
    - common

- name: proxy
  hosts: proxy
  become: yes
  roles:
    - proxy

- name: pihole
  hosts: pihole
  become: yes
  roles:
    - pihole


- name: twitchbot
  hosts: twitchbot
  become: yes
  roles:
    - twitchbot

- name: emote
  hosts: emote
  become: yes
  roles:
    - emote

- name: Fileserver     
  hosts: eye
  become: yes
  roles:
    - fileserver

- name: eye
  hosts: eye
  become: yes
  roles:
    - eye

- name: cam tasks
  hosts: cam
  become: yes
  roles:
    - cam

- name: status
  hosts: status
  become: yes
  roles:
    - status
