---

- name: ansible host
  hosts: ansible
  become: yes
  roles:
    - ansible

- name: common tasks
  hosts: all
  become: yes
  roles:
    - common


- name: pihole
  hosts: pihole
  become: yes
  roles:
    - pihole

- name: twitchbot
  hosts: twitchbot
  become: yes
  roles:
    - twitchbot
  vars:
    web_repo: git@github.com:martyni/web_chat.git

