---

- name: common tasks
  hosts: all
  become: yes
  roles:
    - common


- name: pihole
  hosts: pihole
  become: yes
  roles:
    - pihole

- name: ansible host
  hosts: ansible
  become: yes
  roles:
    - ansible

