---

- name: ansible host
  hosts: ansible
  become: yes
  roles:
    - ansible
  vars:
    repo: git@github.com:martyni/my_network.git

- name: common tasks
  hosts: all
  become: yes
  roles:
    - common


- name: pihole
  hosts: pihole
  become: yes
  roles:
    - pihole
  vars:
    repo: git@github.com:pi-hole/pi-hole.git

- name: twitchbot
  hosts: twitchbot
  become: yes
  roles:
    - twitchbot
  vars:
    repo: git@github.com:martyni/bottymcbotface.git
    web_repo: git@github.com:martyni/web_chat.git

