---

- name: ansible host
  hosts: ansible
  become: yes
  roles:
    - ansible
  vars:
    repo: git@github.com:martyni/my_network.git
    repo_name: my_network

- name: common tasks
  hosts: all
  become: yes
  roles:
    - common

- name: pihole
  hosts: pihole
  become: yes
  roles:
    - pihole
  vars:
    repo: git@github.com:pi-hole/pi-hole.git
    repo_name: pihole

- name: twitchbot
  hosts: twitchbot
  become: yes
  roles:
    - twitchbot
  vars:
    repo: git@github.com:martyni/bottymcbotface.git
    repo_name: bottymcbotface
    web_repo: git@github.com:martyni/web_chat.git
    web_repo_name: app

- name: eye
  hosts: eye
  become: yes
  roles:
    - eye
  vars:
     repo_name: facespin
