---


- name: "Set variables"
  set_fact:
    web_repo: git+http://github.com/martyni/emote_grabber
    web_repo_name: app 

- name: Install emote software
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: gunicorn }
    - { name: firefox }

- name: install emote grabber
  ansible.builtin.pip:
    name: "{{ web_repo }}"


- name: Set hostname
  ansible.builtin.hostname:
    name: emotebot

