---

- name: "Set variables"
  set_fact:
    repo_name: facespin

- name: Install list of packages
  ansible.builtin.file:
    path: "{{ item.name }}"
    state: directory
    owner: "{{ main_user }}"
  with_items:
    - { name: "/home/{{ main_user }}/bcm2835-1.68" }
    - { name: "/home/{{ main_user }}/LCD_Module_RPI_code" }

- name: Extract bcm module 
  ansible.builtin.unarchive:
    src: "http://www.airspayce.com/mikem/bcm2835/bcm2835-1.68.tar.gz"
    dest: "/home/{{ main_user }}/bcm2835-1.68"
    remote_src: yes
    owner: "{{ main_user }}"

- name: Install list of packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: imagemagick }
    - { name: python3-pip }
    - { name: python3-numpy }
    - { name: p7zip-full }

- name: install wiring deb package
  ansible.builtin.apt:
    deb : "https://project-downloads.drogon.net/wiringpi-latest.deb" 


- name: Install list of python packages
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: RPi.GPIO }
    - { name: spidev }
      
- name: install screen dependancies
  ansible.builtin.unarchive:
    src: "https://github.com/martyni/LCD_module/archive/refs/heads/main.zip"
    dest: "/home/{{ main_user }}/LCD_Module_RPI_code"
    remote_src: yes
    owner: "{{ main_user }}"
  register: facespin_code

- name: clone the facespin repo
  ansible.builtin.git:
    repo: https://github.com/martyni/facespin.git
    dest: "/home/{{ main_user }}/{{ repo_name }}"
    force: yes 
    owner: "{{ main_user }}"
  register: facespin_code  

- name: Download Alex face
  become_user: "{{ main_user }}"
  ansible.builtin.get_url:
    url: https://rustyquill.com/wp-content/uploads/2022/01/Newall-Alexander.jpg
    dest: "/home/{{ main_user }}/Pictures/Alex_face.jpg"
  
- name: crop face picture
  become_user: "{{ main_user }}"
  ansible.builtin.command:
    cmd: "/usr/bin/convert  /home/{{ main_user }}/Pictures/Alex_face.jpg -crop 240x240+106+17 /home/{{ main_user }}/Pictures/alexanderjnewall.jpg"
    creates: "/home/{{ main_user }}/Pictures/alexanderjnewall.jpg"
  register: face  

- name: Copy Bot service file accross
  ansible.builtin.template:
    dest: "/etc/systemd/system/facespin.service"
    src: "facespin.service"
  register: systemctl_reread

- name: reread systemctl config files
  ansible.builtin.service:
    daemon_reload: yes
  when: systemctl_reread.changed

- name: ensure facespin service restarted after update
  ansible.builtin.service:
    name: "facespin"
    enabled: yes
    state: restarted
  when: facespin_code.changed or face.changed


- name: ensure face spinning service running
  ansible.builtin.service:
    name: "facespin"
    enabled: yes
    state: started
