---

- name: install screen dependancies
  get_url:
    url: http://www.airspayce.com/mikem/bcm2835/bcm2835-1.68.tar.gz
    dest: "/home/{{ main_user }}/bcm2835-1.68.tar.gz"
    mode: '0740'

- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    remote_src: "/home/{{ main_user }}/bcm2835-1.68.tar.gz"
    dest: "/home/{{ main_user }}/bcm2835-1.68"
    owner: "{{ main_user }}"


- name: Make and install bcm package
  make:
    chdir: "/home/{{ main_user }}/bcm2835-1.68"
    target: install

- name: Install list of packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: wiringpi }
    - { name: python3-pip }
    - { name: python3-numpy }
    - { name: p7zip-full }

- name: Install list of python packages
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: RPi.GPIO }
    - { name: spidev }
      
- name: install screen dependancies
  get_url:
    url: https://www.waveshare.net/w/upload/a/a8/LCD_Module_RPI_code.7z
    dest: "/home/{{ main_user }}/LCD_Module_RPI_code.7z"
    mode: '0740'

- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    remote_src: "/home/{{ main_user }}/LCD_Module_RPI_code.7z"
    dest: "/home/{{ main_user }}/LCD_Module_RPI_code"
    owner: "{{ main_user }}"

- name: add git vars
  become_user: "{{ main_user }}"
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: init.defaultBranch, value: main }
    - { name: user.email, value: "martyn@automationlogic.com"}
    - { name: user.name, value: askMartyn }

