---

- name: Install Ansible
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: ansible }

- name: "Set variables"
  set_fact:
    repo: git@github.com:martyni/my_network.git
    repo_name: my_network

- name: Ensure Ansible code is up to date and stop run if not
  become_user: "{{ main_user }}"
  git:
    repo: "{{ repo }}"
    update: yes
    dest: "/home/{{ main_user }}/repos/{{ repo_name }}"


- name: Ensure Cron ansible job present
  become_user: "{{ main_user }}"
  ansible.builtin.cron:
    name: "Run Ansible"
    minute: "0"
    job: "/home/{{ main_user }}/repos/{{ repo_name }}/run.sh"
      
- name: Create Ansible directory
  ansible.builtin.file:
    path: /etc/ansible/
    state: directory
    recurse: yes
    owner: {{ main_user }}
    group: {{ main_user }}

- name: Ensure ansible host file upto date
  ansible.builtin.copy:
    dest: /etc/ansible/hosts
    src: hosts

- name: Ensure ansible host file upto date
  ansible.builtin.copy:
    dest: /etc/ansible/hosts
    src: hosts

- meta: refresh_inventory

