---

- name: Install Ansible
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: ansible }

- name: "Set variables"
  set_fact:
    repo: git@github.com:martyni/my_network.git
    repo_name: my_network
    remote_host: dev.askmartyn
    log_file: "/home/{{ main_user }}/last_run"

- name: Ensure Ansible code is up to date and stop run if not
  become_user: "{{ main_user }}"
  git:
    repo: "{{ repo }}"
    update: yes
    dest: "/home/{{ main_user }}/repos/{{ repo_name }}"


- name: Ensure Cron ansible job present
  become_user: "{{ main_user }}"
  ansible.builtin.cron:
    name: "Run Ansible"
    minute: "30"
    job: "/home/{{ main_user }}/repos/{{ repo_name }}/run.sh"
      
- name: Create Ansible directory
  ansible.builtin.file:
    path: /etc/ansible/
    state: directory
    owner: "{{ main_user }}"
    group: "{{ main_user }}"

- name: Ensure ansible host file upto date
  ansible.builtin.copy:
    dest: /etc/ansible/hosts
    src: hosts

- name: Ensure ansible host file upto date
  ansible.builtin.copy:
    dest: /etc/ansible/hosts
    src: hosts

- meta: refresh_inventory

- name: ensure ansible2ssh script is present
  ansible.builtin.copy:
    dest: "/home/{{ main_user }}/scripts/"
    src: ansible2ssh.sh

- name: ensure ansible2ssh Cron is enabled
  become_user: "{{ main_user }}"
  ansible.builtin.cron:
    name: "update ssh config"
    job: "/home/{{ main_user }}/scripts/ansible2ssh.sh"

- name: Set hostname
  ansible.builtin.hostname:
    name: ansible

- name: add status sh scripts
  become_user: "{{ main_user }}"
  ansible.builtin.template:
    dest: "/home/{{ main_user }}/scripts/copystatus.sh"
    src: "copystatus.sh"
    mode: u=rwx

- name: Ensure Cron ansible job present
  become_user: "{{ main_user }}"
  ansible.builtin.cron:
    name: "copy_status"
    minute: "*/10"
    job: "cd /home/{{ main_user }}/scripts/; ./copystatus.sh"

- name: add status py scripts
  become_user: "{{ main_user }}"
  ansible.builtin.template:
    dest: "/home/{{ main_user }}/scripts/copystatus.py"
    src: "copystatus.py"
    mode: u=rwx
