---


- name: Cron ansible job
  become_user: "{{ main_user }}"
  ansible.builtin.cron:
    name: "Run Ansible"
    minute: "0"
    job: "/home/{{ main_user }}/repos/{{ repo_name }}/run.sh"
      
- name: Update ansible job
  become_user: "{{ main_user }}"
  git:
    repo: "{{ repo }}"
    update: yes
    dest: "/home/{{ main_user }}/repos/{{ repo_name }}"

- name: ensure host file upto date
  ansible.builtin.copy:
    dest: /etc/ansible/hosts
    src: hosts

- meta: refresh_inventory

