---

- name: Update software and remove older software
  apt:
    update_cache: "yes"
    upgrade: "yes"
    autoremove: "yes"
    purge: "yes"
  when: ansible_os_family == "Debian"

- name: Install list of packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: ansible }
    - { name: vim }
    - { name: git }
    - { name: expect }
    - { name: rpi-imager }

    
- name: add git vars
  become_user: "{{ main_user }}"
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - { name: init.defaultBranch, value: main }
    - { name: user.email, value: "martyn@automationlogic.com"}
    - { name: user.name, value: askMartyn }

