---

- name: Install list of packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: build-essential }
    - { name: cmake }
    - { name: pkg-config }
    - { name: libjpeg-dev }
    - { name: libtiff5-dev }
    - { name: libpng-dev }
    - { name: libavcodec-dev }
    - { name: libavformat-dev }
    - { name: libswscale-dev }
    - { name: libv4l-dev }
    - { name: libxvidcore-dev }
    - { name: libx264-dev }
    - { name: libfontconfig1-dev }
    - { name: libcairo2-dev }
    - { name: libgdk-pixbuf2.0-dev }
    - { name: libpango1.0-dev }
    - { name: libgtk2.0-dev }
    - { name: libgtk-3-dev }
    - { name: libatlas-base-dev }
    - { name: gfortran }
    - { name: libhdf5-dev }
    - { name: libhdf5-serial-dev }
    - { name: libhdf5-103 }
    - { name: libqt5gui5 }
    - { name: libqt5webkit5 }
    - { name: libqt5test5 }
    - { name: python3-pyqt5 }
    - { name: python3-dev }

- name: configure swap memory
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: CONF_SWAPSIZE=2048

- name: Install list of packages
  ansible.builtin.pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: virtualenv }
    - { name: opencv-contrib-python }
