---

- name: Install list of packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: cmake }
    - { name: build-essential }
    - { name: pkg-config }
    - { name: libjpeg-dev }
    - { name: libjasper-dev }
    - { name: libpng-dev }
    - { name: libwebp-dev }
    - { name: libopenexr-dev }
    - { name: libavcodec-dev }
    - { name: libavformat-dev }
    - { name: libswscale-dev }
    - { name: libv4l-dev }
    - { name: libxvidcore-dev }
    - { name: libx264-dev }
    - { name: libdc1394-22-dev }
    - { name: libgstreamer-plugins-base1.0-dev }
    - { name: libgstreamer1.0-dev }
    - { name: libgtk-3-dev }
    - { name: libqtgui4 }
    - { name: libqtwebkit4 } 
    - { name: libqt4-test }
    - { name: python3-pyqt5 }
    - { name: libatlas-base-dev }
    - { name: liblapacke-dev }
    - { name: gfortran }
    - { name: libhdf5-dev }
    - { name: libhdf5-103 }
    - { name: python3-dev }
    - { name: python3-pip }
    - { name: python3-numpy }

- name: configure swap memory
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: CONF_SWAPSIZE=2048

- name: Update opencv
  become_user: "{{ main_user }}"
  git:
    repo: "https://github.com/opencv/opencv.git"
    dest: "/home/{{ main_user }}/repos/opencv"

- name: Update opencv contrib
  become_user: "{{ main_user }}"
  git:
    repo: "https://github.com/opencv/opencv_contrib.git"
    dest: "/home/{{ main_user }}/repos/opencv_contrib"

- name: create build directory
  ansible.builtin.file:
     path: "/home/{{ main_user }}/repos/opencv/build"
     state: directory
