---


- name: Install list of packages
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: curl }

      

- name: Update pihole local repo
  become_user: "{{ main_user }}"
  git:
    repo: "{{ repo }}"
    update: yes
    dest: "/home/{{ main_user }}/repos/{{ repo_name }}"
  register: pihole


- name: Set hostname
  ansible.builtin.hostname:
      name: pihole
